### ISSUE TITLE
error: static assertion failed: Missing cg.templatable(...)

### ISSUE THREAD

**Issue by 1iverea9er** [slimcdk/esphome-custom-components#46]
After update ESPHome to 2026.4.5 (or bit erlier..)

src/esphome/core/automation.h:70:29: error: static assertion failed: Missing cg.templatable(...) in Python codegen for this TEMPLATABLE_VALUE field. The wrapper was always required; it worked by accident because the old TemplatableValue implicitly converted raw constants. TemplatableFn cannot. See https://developers.esphome.io/blog/2026/04/09/templatablefn-4-byte-templatable-storage-for-trivially-copyable-types/
   70 |     static_assert(sizeof(V) == 0, "Missing cg.templatable(...) in Python codegen for this TEMPLATABLE_VALUE "
      |                   ~~~~~~~~~~^~~~
src/esphome/core/automation.h:70:29: note: the comparison reduces to '(1 == 0)'

[logs_trv-br-stepper_run.txt](https://github.com/user-attachments/files/27950222/logs_trv-br-stepper_run.txt)

**Comment by daniel-frenkel** [comment]
Here's what Clause says about this warning:

Those are deprecation warnings, not errors — your build succeeded. They originate inside the external tmc2209 component (slimcdk's custom components), not your YAML.

**What the warning means**
ESPHome recently tightened its codegen check: a !lambda (or even a literal value) wired into a templatable field must return exactly the C++ type that field expects. The slimcdk component declares:

1. microsteps: uint16_t
2. stallguard_threshold: int32_t

…but the lambdas being generated for them return plain int. Even when int and int32_t are the same width on ESP32, the compiler treats them as nominally distinct, so it flags the mismatch. This warning will become a hard error around ESPHome 2026.7.0 (same deadline as the / warning).

**Two paths forward**
1. Ignore for now — it's a third-party-component issue and the firmware still compiles and runs. The proper fix is in slimcdk's codegen; worth opening an issue at https://github.com/slimcdk/esphome-custom-components.

2. Silence locally by forcing exact return types in the lambdas. In the on_boot: block, swap to:

- tmc2209.configure:
    direction: !lambda "return id(global_stepper_direction);"
    microsteps: !lambda "return (uint16_t) 8;"
    interpolation: true
    tcool_threshold: !lambda "return (int32_t) id(global_tcoolthrs);"
- tmc2209.stallguard:
    threshold: !lambda "return (int32_t) id(global_sgthrs);"

Note: the tcool_threshold cast is a guess (TCOOLTHRS is a 20-bit register, so the field might be int32_t or uint32_t); the SGTHRS one matches the warning exactly. If the second warning persists after casting, swap to uint32_t for tcool_threshold.

**Comment by slimcdk** [comment]
Do you mind testing the changes on branch `fix-breaking-changes`?

**Comment by 1iverea9er** [comment]
I tried the following link 
```
external_components:
  - source: github://slimcdk/esphome-custom-components/tree/fix-breaking-changes
    components: [ tmc2209_hub, tmc2209, stepper ]
```
The result is the same as before

**Comment by daniel-frenkel** [comment]
I tested it as well, and there is one less warning, but the issue is still there. Here's what Claude recommends:

On the latest ESPHome the TMC2209 templatable actions emit a deprecation warning that will become a hard error around ESPHome 2026.7.0. Example:

```
src/esphome/components/tmc2209/automation.h: In instantiation of
'void esphome::tmc2209::StallGuardAction<Ts>::set_stallguard_threshold(V) ...':
warning: ... [with F = setup()::<lambda()>; T = long int; ...]
  is deprecated: Lambda return type does not match TemplatableFn<T>
  — use the correct type in codegen [-Wdeprecated-declarations]
src/esphome/components/tmc2209/automation.h:100:3:
  TEMPLATABLE_VALUE(int32_t, stallguard_threshold)
```

## Root cause

The C++ side declares the field correctly:

```cpp
TEMPLATABLE_VALUE(int32_t, stallguard_threshold)
```

…which generates `set_stallguard_threshold<F>(F)` requiring `F`'s return type to be `int32_t`. But the Python codegen is calling `cg.templatable()` with the wrong type argument, so it emits a lambda returning plain `int` (`long int` on this target). ESPHome's recently-tightened template constraint flags the mismatch.

The `fix-breaking-changes` branch already handled `set_microsteps` (`uint16_t`) this way, but `set_stallguard_threshold` and likely a few others were missed.

## The fix

In the component's Python codegen, the third argument of `cg.templatable()` must match the type passed to `TEMPLATABLE_VALUE` on the C++ side. Something like:

```python
# before
template_ = await cg.templatable(config[CONF_THRESHOLD], args, int)
cg.add(var.set_stallguard_threshold(template_))

# after
template_ = await cg.templatable(config[CONF_THRESHOLD], args, cg.int32)
cg.add(var.set_stallguard_threshold(template_))
```

Mapping table (apply to every templatable field):

| C++ side                                            | Python side                          |
| --------------------------------------------------- | ------------------------------------ |
| `TEMPLATABLE_VALUE(uint8_t,  irun)`                 | `cg.templatable(..., cg.uint8)`      |
| `TEMPLATABLE_VALUE(uint16_t, microsteps)`           | `cg.templatable(..., cg.uint16)`     |
| `TEMPLATABLE_VALUE(int32_t,  stallguard_threshold)` | `cg.templatable(..., cg.int32)`      |
| `TEMPLATABLE_VALUE(uint32_t, tcool_threshold)`      | `cg.templatable(..., cg.uint32)`     |

## How to find every offender

```
grep -n TEMPLATABLE_VALUE components/tmc2209/*.h
grep -n "cg.templatable(" components/tmc2209/*.py
```

…then verify each `cg.templatable()` call passes the `cg.<type>` matching the corresponding `TEMPLATABLE_VALUE` declaration.

## Why it used to work

ESPHome used to silently coerce — a lambda returning `int` was accepted for a field expecting `int32_t`. The new constraint catches width/sign mismatches (`int32_t` field fed by a `uint64_t` lambda, etc.) at compile time instead of letting them silently truncate.

## User-side workaround until this lands

In the meantime, casting in the YAML lambda silences the warning:

```yaml
- tmc2209.stallguard:
    threshold: !lambda "return (int32_t) id(global_sgthrs);"
```

**Comment by slimcdk** [comment]
> I tried the following link
> 
> ```
> external_components:
>   - source: github://slimcdk/esphome-custom-components/tree/fix-breaking-changes
>     components: [ tmc2209_hub, tmc2209, stepper ]
> ```
> 
> The result is the same as before

You specify the branch like this (with `@`). I have pushed more updates to the branch as well.

```yaml
external_components:
  - source: github://slimcdk/esphome-custom-components@fix-breaking-changes
    components: [ tmc2209_hub, tmc2209, stepper ]
```

**Comment by 1iverea9er** [comment]
Yes, the code from this branch compiles without critical errors. Only minor warnings remain (Apparently I configured something incorrectly):
```
WARNING tmc2209.stallguard on 'driver' sets SGTHRS but no tmc2209.configure for the same driver sets `tcool_threshold`. The TMC2209 keeps StallGuard gated OFF unless the motor's TSTEP is below TCOOLTHRS, so DIAG will never rise from a stall. Add e.g. `tmc2209.configure: { tcool_threshold: 400 }` to your on_boot. (See issue #45.)
```

Upd:
After adding the `tcool_threshold` setting to `tmc2209.configure`, the logs are clean. 

Thanks !
